Feature/facelift
colucom/CLN-community-app pull request #276
Opened 2019-06-12 12:57 UTC by LiorAgnin

## Proposed changes

- Facelift

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

2019-06-13 08:10 UTC, leonprou requested changes
Looks good. very clean.
Some small comments, recommendations mostly.

Check please that bug with communityEntity override to see its behaviour

2019-06-13 08:10 UTC, leonprou commented on dapp/src/components/home/components/FeaturedCommunities/index.jsx
> +  ...state.screens.oven
should rename the `oven` to better name like `home`

2019-06-13 08:10 UTC, leonprou commented on dapp/src/reducers/accounts.js
> +  [actions.FETCH_COMMUNITIES.SUCCESS]: (state, action) => {
try to put just the community addresses here

2019-06-13 08:10 UTC, leonprou commented on dapp/src/sagas/accounts.js
> +function * fetchCommunities ({ account }) {
I think you can use `createEntitiesFetch` to create this action

2019-06-16 13:09 UTC, LiorAgnin commented on dapp/src/sagas/accounts.js
> +function * fetchCommunities ({ account }) {
Done

2019-06-16 13:09 UTC, LiorAgnin commented on dapp/src/reducers/accounts.js
> +  [actions.FETCH_COMMUNITIES.SUCCESS]: (state, action) => {
Done

2019-06-16 13:09 UTC, LiorAgnin commented on dapp/src/components/dashboard/pages/Businesses/index.jsx
> +    const { transactionStatus, merchants } = this.props
Done

2019-06-16 13:09 UTC, LiorAgnin commented on dapp/src/components/dashboard/containers/MainDashboard/index.jsx
> +  token: state.entities.communities &&
Already exist

2019-06-16 13:09 UTC, LiorAgnin commented on dapp/src/components/dashboard/components/Header/index.jsx
> +          isDaiToken={token && token.symbol === 'DAI'}
Done

2019-06-16 13:10 UTC, LiorAgnin commented on dapp/src/components/common/ProfileDropDown/index.jsx
> +            <React.Fragment>
Done

2019-06-16 13:16 UTC, leonprou approved these changes
👍

2019-06-16 14:36 UTC, merged